### ISSUE TITLE
img src gets mangled on some images

### ISSUE THREAD

**Issue by kxt** [hipstermojo/paperoni#13]
Produced with version `0.4.0-alpha1`

Some pages have some of their `img src` attributes changed by the readibility code, resulting in broken urls that causes error 404 during fetching.

One page where I've noticed this bug is https://blindsquirrel.substack.com/p/etsy-the-power-of-special

Here the first image ("Strong & Competitive Market Position") gets mangled. It's `img` node is this (it's quite funky and has a data-attrs attribute, but the src url works):
```
<img src="https://cdn.substack.com/image/fetch/w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fbucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com%2Fpublic%2Fimages%2F7ba6067a-991d-47a0-b1ea-b24adf135f82_1099x454.png" data-attrs="{&quot;src&quot;:&quot;https://bucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com/public/images/7ba6067a-991d-47a0-b1ea-b24adf135f82_1099x454.png&quot;,&quot;height&quot;:454,&quot;width&quot;:1099,&quot;resizeWidth&quot;:null,&quot;bytes&quot;:177952,&quot;alt&quot;:null,&quot;title&quot;:null,&quot;type&quot;:&quot;image/png&quot;,&quot;href&quot;:null}" alt="">
```

Then somehow during readibility processing `src` attribute gets changed to this value, appears to be the same as `data-attrs` attribute value, just url-decoded (the \ escaping is introduced during logging):
```
{\"src\":\"https://bucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com/public/images/7ba6067a-991d-47a0-b1ea-b24adf135f82_1099x454.png\",\"height\":454,\"width\":1099,\"resizeWidth\":null,\"bytes\":177952,\"alt\":null,\"title\":null,\"type\":\"image/png\",\"href\":null}
```

As it no longer looks like an absolute url (starts with `{"src": "https://` instead of `https://`), `fix_relative_uris` will prepend the original base url, `https://blindsquirrel.substack.com/p/`, resulting in this broken url: 
```
https://blindsquirrel.substack.com/p/%7B%22src%22:%22https://bucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com/public/
images/7ba6067a-991d-47a0-b1ea-b24adf135f82_1099x454.png%22,%22height%22:454,%22width%22:1099,%22resizeWidth%22:null,%22bytes%22:177952,%22alt%22:null,%22title%22:null,%22type%22:%22image/png%22,%22href%22:null%7D, new_url=https://blindsquirrel.substack.com/p/%7B%22src%22:%22https://bucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com/public/images/7ba6067a-991d-47a0-b1ea-b24adf135f82_1099x454.png%22,%22height%22:454,%22width%22:1099,%22resizeWidth%22:null,%22bytes%22:177952,%22alt%22:null,%22title%22:null,%22type%22:%22image/png%22,%22href%22:null%7D
```

The weird thing is that not all images have this problem. Here's an `img` node that does not get mangled:
```
<img src="https://cdn.substack.com/image/fetch/w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fbucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com%2Fpublic%2Fimages%2F9f4b3eaa-0537-403d-b9c8-a91f88724cc8_959x617.png" data-attrs="{&quot;src&quot;:&quot;https://bucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com/public/images/9f4b3eaa-0537-403d-b9c8-a91f88724cc8_959x617.png&quot;,&quot;height&quot;:617,&quot;width&quot;:959,&quot;resizeWidth&quot;:576,&quot;bytes&quot;:null,&quot;alt&quot;:&quot;Focus on Marketplace \nin Six Core Geographies \nCore markets have our largest concentrations ofbuyers and \nsellers and present the most significant growth opportunities \nTOP GEOGRAPHIES: \nWe are building local marketplaces globally and deepening \nlocal Etsy communities globally \nLarge and Growing Addressable Market \nEstimated 2018 Total Retail and Online TAM \nSl.7T \neat \n049B \nto ALL \nretail top geqraphies \n-SIOOB \nGER \&quot;ANY \n8.9B \n2018 GLOBAL GMS \nETSY MARKET SHARE &quot;,&quot;title&quot;:null,&quot;type&quot;:null,&quot;href&quot;:null}" alt="Focus on Marketplace
in Six Core Geographies
Core markets have our largest concentrations ofbuyers and
sellers and present the most significant growth opportunities
TOP GEOGRAPHIES:
We are building local marketplaces globally and deepening
local Etsy communities globally
Large and Growing Addressable Market
Estimated 2018 Total Retail and Online TAM
Sl.7T
eat
049B
to ALL
retail top geqraphies
-SIOOB
GER &quot;ANY
8.9B
2018 GLOBAL GMS
ETSY MARKET SHARE ">
```
The only difference I've noticed is that every `img` node that fails has an `alt=""` attribute and every good `img` has a non-empty `alt` attribute.

**Comment by kxt** [comment]
I created a reduced testcase for `moz_readibility/mod.rs` that reproduces the issue.
```
    #[test]
    fn test_issue_13() {
        macro_rules! check_img_src_prefix {
            ($html:expr, $expected_prefix:expr) => {
                let mut doc = Readability::new($html);
                doc.parse("https://original.url/")
                    .expect("Should parse successfully");
                let img = doc
                    .article_node
                    .unwrap()
                    .select("img")
                    .unwrap()
                    .next()
                    .unwrap();
                let expected_prefix = "https://image.url";
                let attrs = img.attributes.borrow();
                let actual_url = attrs.get("src").unwrap();
                assert!(
                    actual_url.starts_with(expected_prefix),
                    "url should start with {}, url={}",
                    $expected_prefix,
                    actual_url
                );
            };
        }

        // generate an html string with an img tag that has a 'data-attrs' attribute that contains an 'alt' key having the value ALT_TEXT
        macro_rules! alt_text {
            ($ALT_TEXT:expr) => {
                concat!(r#"
                <html><body>
                    Text
                    <img src="https://image.url/" data-attrs="{{&quot;src&quot;:&quot;https://other.url/1.png&quot;,&quot;alt&quot;:&quot;"#, $ALT_TEXT, r#"&quot;}}"/>
                </body></html>
            "#)
            }
        }

        let expected_prefix = "https://image.url";

        check_img_src_prefix!(alt_text!("STUFF WITH SPACE"), expected_prefix); // OK
        check_img_src_prefix!(alt_text!("STUFF_WITHOUT_SPACES"), expected_prefix); // FAiLS
    }
```
What I noticed:
* `data-attrs` must contain an `src` with an url that ends with a recognized image extension, if I change `png` to `pnx` both checks pass
* If `alt` contains anything with a space, it passes.

I haven't found the code that does anything with `data-attrs` yet.

**Comment by kxt** [comment]
The issue is with `fix_lazy_images`:
```
            let src = node_attr.get("src");
            let srcset = node_attr.get("srcset");
            let class = node_attr.get("class");
            if (src.is_some() || srcset.is_some())
                && class.is_some()
                && !class.unwrap().contains("lazy")
            {
                continue;
            }
```
Here, if `node_attr` has no `class` attribute, the condition becomes false and carries on replacing `src`.

In the original .js code the condition is `((elem.src || (elem.srcset && elem.srcset != "null")) && elem.className.toLowerCase().indexOf("lazy") === -1)`. The trick is that the DOM property `className` always exists, it's just unpopulated if the HTML attribute does not exist.

Preparing a PR with the fix.

However, there remains a lingering issue: what if `img` happens to have a class that has `lazy` in it? Replacing `src` with something that starts with `{\"src\":\"https://` would certainly not be a good idea.

**Comment by hipstermojo** [comment]
This is honestly really good! I really need to improve the unit testing of the readability module, but that is why it's still in alpha after all. Please change this to merge to `dev` instead of `master`. Thank you for taking your time to solve this and adding a test for it.

> However, there remains a lingering issue: what if img happens to have a class that has lazy in it? Replacing src with something that starts with {\"src\":\"https:// would certainly not be a good idea.

Unfortunately, different websites have different ways of handling lazy loading of assets and with browsers bringing up lazy loading natively, I think I'd have to go on a case-by-case scenario of finding fixes for these problems.

**Comment by kxt** [comment]
I've updated the PR for dev branch and fixed a typo in the commit messages.

Honestly, I was delighted to see this many tests in a small open-source project. It made hunting the bug down easier because I just plopped offending tag into the relevant test case and played around with it until I figured out what's happening.

I see that `moz_readability.rs` follows the structure of `Readability.js` faithfully, which makes it easier to find translation bugs like this one and to keep up with updates in `Readability.js`. Also means that it's not really rustic and we can't make changes to the algorithm.

What is your policy about ad-hoc changes to moz_readability?

With this PR, the issues I had with substack.com pages are solved, so I can leave it at that, but I might just come up with a heuristic for handling `data-attrs` sometime in the future. Would you accept a PR like that?

**Comment by hipstermojo** [comment]
> What is your policy about ad-hoc changes to moz_readability?

I wouldn't call this one an ad-hoc change really since it exposes a bug that doesn't show up in the .js source code. Unless a change involves changing the logic significantly I am welcome to them especially since some parts of the code are still not covered with tests.

> ... but I might just come up with a heuristic for handling data-attrs sometime in the future. Would you accept a PR like that?

While this is great, I'd like to keep the readability module as close to the original implementation as possible, because in future, I'd want to move it into its own crate. Before this can happen, however, I'd like to also port the test suite from the .js version.

**Comment by hipstermojo** [comment]
I'll leave this issue open until Wednesday in case you have any more questions.

**Comment by kxt** [comment]
I do understand your motivation on keeping the readability module close to the original. With this fix, paperoni works just fine for my web archival needs, this issue can be closed.
